NAMES = {
"laptops": [
"ZenBook X14","ZenBook Pro 16","ZenBook S14","ZenBook Flip 15","ZenBook Air 13",
"ThinkMate Pro 15","ThinkMate Edge 14","ThinkMate X1 16","ThinkMate Slim 13","ThinkMate Carbon 14",
"SwiftCore Air 13","SwiftCore Go 14","SwiftCore Plus 15","SwiftCore Ultra 16","SwiftCore Lite 11",
"CreatorBook Studio 16","CreatorBook Pro 15","CreatorBook Pen 14","CreatorBook Vision 17","CreatorBook Mini 13",
"GameForge G15","GameForge Titan 17","GameForge Strike 16","GameForge Blaze 15","GameForge Edge 14",
"TravelMate Lite 14","TravelMate Spin 13","TravelMate Go 11","TravelMate Flex 15","TravelMate Core 14",
"CodeBook Edge 14","CodeBook Dev 15","CodeBook Prime 16","CodeBook Air 13","CodeBook Studio 15",
"UltraNote Flex 13","UltraNote Pro 14","UltraNote Slim 15","UltraNote Touch 16","UltraNote SE 14",
"WorkPro Elite 15","WorkPro Max 17","WorkPro Dock 16","WorkPro Go 14","WorkPro Nano 13",
"NimbusBook S16","NimbusBook Air 14","NimbusBook Pro 15","NimbusBook Lite 13","NimbusBook Edge 15",
"SpectraBook X15","SpectraBook Duo 14","SpectraBook Fold 16","SpectraBook Slim 13","SpectraBook One 14",
"FlexNote Z14","FlexNote Spin 15","FlexNote Tab 13","FlexNote Max 16","FlexNote Duo 14",
"IronBook Rugged 14","IronBook Shield 15","IronBook Tank 16","IronBook Core 14","IronBook Field 13",
"AirEdge Ultra 13","AirEdge Slim 14","AirEdge Feather 12","AirEdge Pro 15","AirEdge Go 11",
"StormBook Fury 17","StormBook Bolt 15","StormBook Thunder 16","StormBook Flash 14","StormBook Rage 15",
"CloudNote Sky 14","CloudNote Drift 13","CloudNote Breeze 15","CloudNote Haze 14","CloudNote Mist 12",
"TechPad Alpha 15","TechPad Sigma 14","TechPad Delta 16","TechPad Omega 13","TechPad Beta 14",
"PowerBook Surge 15","PowerBook Volt 16","PowerBook Amp 14","PowerBook Watt 13","PowerBook Grid 15",
"LiteBook Feather 13","LiteBook Whisper 14","LiteBook Pebble 12","LiteBook Leaf 13","LiteBook Silk 14",
"ProEdge Vertex 15","ProEdge Apex 16","ProEdge Summit 14","ProEdge Peak 17","ProEdge Crest 15",
],
"smartphones": [
"PixelMax Pro","PixelMax Ultra","PixelMax Mini","PixelMax Lite","PixelMax SE",
"GalaxyWave S24","GalaxyWave S24 Ultra","GalaxyWave A55","GalaxyWave M14","GalaxyWave F34",
"OnePlus Nova 12","OnePlus Nova 12R","OnePlus Nova Pro","OnePlus Nova CE","OnePlus Nova Nord",
"MotoEdge Fusion","MotoEdge Razor","MotoEdge Neo","MotoEdge Power","MotoEdge Style",
"LumaPhone X2","LumaPhone X3 Pro","LumaPhone Slim","LumaPhone Max","LumaPhone Air",
"AeroPixel Mini","AeroPixel Plus","AeroPixel Ultra","AeroPixel SE","AeroPixel Fold",
"VivoSpark Plus","VivoSpark Pro","VivoSpark Neo","VivoSpark Lite","VivoSpark X1",
"RedmiPulse Note","RedmiPulse Pro","RedmiPulse Max","RedmiPulse Turbo","RedmiPulse Core",
"ZenMobile Ultra","ZenMobile Flip","ZenMobile Compact","ZenMobile Edge","ZenMobile Prime",
"NordLine 5G","NordLine Pro","NordLine Ace","NordLine Lite","NordLine X",
"StellarPhone Alpha","StellarPhone Beta","StellarPhone Gamma","StellarPhone Delta","StellarPhone Omega",
"NexaVolt Z1","NexaVolt Z2 Pro","NexaVolt Z3 Max","NexaVolt Z1 Lite","NexaVolt Z4",
"OrbitX Pro","OrbitX Mini","OrbitX Ultra","OrbitX SE","OrbitX Plus",
"TrueCall Prime","TrueCall Max","TrueCall Lite","TrueCall Neo","TrueCall Edge",
"BlitzPhone Rapid","BlitzPhone Flash","BlitzPhone Swift","BlitzPhone Nitro","BlitzPhone Dash",
"CrystalView C10","CrystalView C12 Pro","CrystalView C8","CrystalView C15","CrystalView C10 Lite",
"QuantumQ Pro","QuantumQ Max","QuantumQ Flip","QuantumQ Slim","QuantumQ Edge",
"PrimeCell One","PrimeCell Two Pro","PrimeCell Three","PrimeCell Mini","PrimeCell Ultra",
"EchoWave E5","EchoWave E7 Pro","EchoWave E3","EchoWave E9 Max","EchoWave E5 Lite",
"VoltEdge V1","VoltEdge V2","VoltEdge V3 Pro","VoltEdge V1 SE","VoltEdge V4 Ultra",
],
"headphones": [
"SoundCore Horizon","SoundCore Aura","SoundCore Zen","SoundCore Pulse","SoundCore Wave",
"AudioPeak Studio","AudioPeak Live","AudioPeak DJ","AudioPeak Mix","AudioPeak Solo",
"BassDrop XR","BassDrop Pro","BassDrop Ultra","BassDrop Mini","BassDrop Core",
"QuietMind ANC","QuietMind Pro","QuietMind Max","QuietMind Lite","QuietMind Focus",
"PulseBeats 700","PulseBeats 500","PulseBeats 900","PulseBeats 300","PulseBeats 100",
"SonicEdge Flex","SonicEdge Air","SonicEdge Pro","SonicEdge Sport","SonicEdge Clip",
"HarmonyPods Pro","HarmonyPods Lite","HarmonyPods Max","HarmonyPods Sport","HarmonyPods Mini",
"ToneMaster Elite","ToneMaster Classic","ToneMaster Studio","ToneMaster Live","ToneMaster Neo",
"FreqWave X1","FreqWave X3","FreqWave X5","FreqWave X7","FreqWave X9",
"ClearTone Halo","ClearTone Ring","ClearTone Arc","ClearTone Beam","ClearTone Orb",
"NoiseFade Calm","NoiseFade Serene","NoiseFade Bliss","NoiseFade Still","NoiseFade Peace",
"RhythmFlow Beat","RhythmFlow Groove","RhythmFlow Tempo","RhythmFlow Sync","RhythmFlow Vibe",
"DeepBass Rumble","DeepBass Thunder","DeepBass Quake","DeepBass Boom","DeepBass Drop",
"AirBud Comfort","AirBud Active","AirBud Sleep","AirBud Travel","AirBud Daily",
"EchoSphere Open","EchoSphere Closed","EchoSphere Semi","EchoSphere Flat","EchoSphere Wide",
"VocalEdge Talk","VocalEdge Call","VocalEdge Meet","VocalEdge Podcast","VocalEdge Voice",
"ZenAudio Relax","ZenAudio Focus","ZenAudio Sleep","ZenAudio Calm","ZenAudio Flow",
"ProSound Monitor","ProSound Reference","ProSound Flat","ProSound Stage","ProSound Booth",
"WaveRider Surf","WaveRider Drift","WaveRider Cruise","WaveRider Coast","WaveRider Glide",
"BeatForge Iron","BeatForge Steel","BeatForge Brass","BeatForge Chrome","BeatForge Copper",
],
"monitors": [
"VisionPro 27QHD","VisionPro 32UHD","VisionPro 24FHD","VisionPro 34UW","VisionPro 27FHD",
"SpectraView S27","SpectraView S32","SpectraView S24","SpectraView S34","SpectraView S28",
"PixelEdge 4K 27","PixelEdge 4K 32","PixelEdge QHD 27","PixelEdge FHD 24","PixelEdge UW 34",
"ClearSight Pro 27","ClearSight Pro 32","ClearSight Duo 24","ClearSight Wide 34","ClearSight Elite 28",
"ColorMaster Studio 27","ColorMaster Studio 32","ColorMaster Edit 27","ColorMaster Print 24","ColorMaster Grade 32",
"GameView GX27","GameView GX32","GameView GX24","GameView GX34","GameView GX27C",
"UltraFrame 240Hz","UltraFrame 165Hz","UltraFrame 144Hz","UltraFrame 75Hz","UltraFrame 360Hz",
"LuminEdge HDR 27","LuminEdge HDR 32","LuminEdge SDR 24","LuminEdge HDR 34","LuminEdge Pro 28",
"SharpDesk Curve 34","SharpDesk Flat 27","SharpDesk Mini 24","SharpDesk Wide 38","SharpDesk Slim 27",
"TrueColor Artist 27","TrueColor Artist 32","TrueColor Coder 27","TrueColor Office 24","TrueColor Photo 27",
"MonoView Clean 27","MonoView Clean 32","MonoView Bright 24","MonoView Sharp 28","MonoView Slim 24",
"DualEdge Split 32","DualEdge Split 27","DualEdge KVM 34","DualEdge Hub 27","DualEdge Link 28",
"NanoPanel IPS 27","NanoPanel VA 32","NanoPanel OLED 27","NanoPanel TN 24","NanoPanel IPS 32",
"EyeCare Flicker 27","EyeCare Blue 24","EyeCare Matte 27","EyeCare Comfort 32","EyeCare Soft 24",
"ProFrame Cinema 32","ProFrame Cinema 27","ProFrame Edit 34","ProFrame Grade 27","ProFrame View 24",
"HyperSync 240 27","HyperSync 165 32","HyperSync 144 27","HyperSync 360 24","HyperSync 120 34",
"CrispView Retina 27","CrispView Retina 32","CrispView HD 24","CrispView UHD 28","CrispView QHD 27",
"StudioLux Calibr 27","StudioLux Calibr 32","StudioLux Basic 24","StudioLux Wide 34","StudioLux Pen 27",
"ZenScreen Portable 15","ZenScreen Portable 17","ZenScreen Touch 15","ZenScreen OLED 13","ZenScreen USB 16",
"PanelForge Tough 27","PanelForge Tough 32","PanelForge Flex 24","PanelForge Mount 34","PanelForge Stand 27",
],
}
